server:
  port: 8080

spring:
  application:
    name: cafe
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #    url: ${DB_URL}
    #    username: ${DB_USERNAME}
    #    password: ${DB_PASSWORD}
    url: jdbc:mariadb://localhost:3306/team9?createDatabaseIfNotExist=true
    # createDatabaseIfNotExist=true 데이터베이스가 없을 경우 생성
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update # 엔티티로 등록된 클래스와 매핑되는 테이블 자동 생성 주석해도 됩니다.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
          # 자바에서 카멜로 필드 작성하면 DB에 스네이크로 기록
    properties:
      hibernate:
        show_sql: true
#        format_sql: true # 이쁘게 보기